### ISSUE TITLE
faraday-multipart 1.1.0と合わせるとエラーが発生

### ISSUE THREAD

**Issue by t-kinoshita** [asonas/chatwork-ruby#89]
faraday-multipartを1.1.0にアップデートしたところ、以下のエラーが発生しました（faraday-multipart 1.0.4では正常動作）。

```
NoMethodError: undefined method `mime_type=' for ChatWork::Multipart:Class
/usr/local/bundle/gems/chatwork-1.0.0/lib/chatwork/multipart.rb:3:in `<class:Multipart>'
/usr/local/bundle/gems/chatwork-1.0.0/lib/chatwork/multipart.rb:2:in `<module:ChatWork>'
/usr/local/bundle/gems/chatwork-1.0.0/lib/chatwork/multipart.rb:1:in `<main>'
```

多少追いかけてはみたものの、原因は特定できませんでした。

なお、Rubyは2.7.8をx64 Linuxで動かしています。また、faraday関連のGem状況は以下のとおりです。

```
    faraday (2.8.1)
      base64
      faraday-net_http (>= 2.0, < 3.1)
      ruby2_keywords (>= 0.0.4)
    faraday-mashify (0.1.1)
      faraday (~> 2.0)
      hashie
    faraday-net_http (3.0.2)
```

**Comment by sue445** [comment]
@t-kinoshita 報告ありがとうございます。 #90 で修正してv1.0.1をリリースしました。

https://github.com/asonas/chatwork-ruby/releases/tag/v1.0.1
